### PR TITLE
Create maven.yml

### PR DESCRIPTION
**Pull request by laeubi**
It would be good if PRs can be verified at a very basic level.

### CODE REVIEW

**Comment by laeubi** [comment]
@cstamas maybe a first step to attract more contributions :-)

**Comment by cstamas** [comment]
I would rather create a new repo as we end up copy-paste all these around: The "dusted off" projects already have these (copies):
https://github.com/takari/takari-pom/blob/master/.github/workflows/ci.yml
https://github.com/takari/takari-plugin-testing-project/blob/master/.github/workflows/ci.yml
https://github.com/takari/takari-lifecycle/blob/master/.github/workflows/ci.yml

So let's create a new repo and just share, instead to copy paste?

**Comment by cstamas** [comment]
Created https://github.com/takari/takari-gh-actions (based on ASF Maven repo w/ takari ci.yml)

**Comment by cstamas** [comment]
Example https://github.com/takari/takari-pom/pull/11
pls adjust this PR. Also, you can create PR against shared workflows as well if needed.

**Comment by laeubi** [comment]
I'm not familiar with shared workflows, but should shared stuff not go into a `.gtihub` repo? At alest this seems the way to go for shared contribution and alike:

https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/creating-a-default-community-health-file

**Comment by cstamas** [comment]
https://github.com/takari/takari-smart-builder/pull/18

**Comment by cstamas** [comment]
merged #18, pls close this out if ok

**Pull request closed without merging**
